import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Rocket } from "lucide-react";
import { CampaignGrid } from "@/components/campaigns/campaign-grid";
import { Campaign } from "@/components/campaigns/campaign-card";

const campaigns: Campaign[] = [
  {
    id: 'decentralized-ai-1',
    title: 'Project Gaia: Decentralized AI for Climate Change',
    description: 'An open-source AI model to analyze climate data and predict environmental impacts.',
    longDescription: 'Project Gaia aims to build a globally accessible, decentralized AI platform focused on climate change. By training our models on publicly available datasets, we can provide transparent and verifiable predictions for sea-level rise, deforestation, and extreme weather events, empowering communities and policymakers to take effective action.',
    imageId: 'img-ai-climate',
    goal: 150,
    currency: 'ETH',
    currentAmount: 95,
    donors: 450,
    endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active',
  },
  {
    id: 'web3-education-2',
    title: 'Metis: Learn-to-Earn Web3 Education Platform',
    description: 'Gamified quests and tutorials to onboard the next million users to Web3, with token rewards.',
    longDescription: 'Metis is a learn-to-earn platform designed to make entering the world of Web3 simple and rewarding. Users complete interactive tutorials on wallets, DeFi, and NFTs, earning tokens for each skill they master. Our goal is to break down the barriers to entry and foster a knowledgeable and engaged community.',
    imageId: 'img-web3-learn',
    goal: 50,
    currency: 'ETH',
    currentAmount: 12,
    donors: 180,
    endDate: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active',
  },
   {
    id: 'art-generator-3',
    title: 'Chroma Collective: AI-Generated Art NFTs',
    description: 'A platform for creating and minting unique art pieces generated by collaborative AI models.',
    longDescription: 'Chroma Collective empowers artists and collectors to collaborate with AI. Our platform uses generative models trained on classical and modern art to produce stunning, unique digital creations. Each piece can be minted as an NFT, with shared ownership between the human prompter and the AI, creating a new paradigm for digital art.',
    imageId: 'img-art-ai',
    goal: 75,
    currency: 'BTC',
    currentAmount: 61,
    donors: 320,
    endDate: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active',
  },
];

const completedCampaigns: Campaign[] = [
    {
    id: 'open-source-library-4',
    title: 'Ethos.js: Open-Source Web3 Library',
    description: 'Successfully funded a new lightweight library for simpler smart contract interactions.',
    longDescription: 'Ethos.js was created to simplify the developer experience in Web3. Thanks to our 500+ backers, we have developed a powerful, lightweight JavaScript library that abstracts away the complexities of blockchain interaction, making it easier than ever to build decentralized applications. The library is now open-source and available on NPM.',
    imageId: 'img-open-source',
    goal: 25,
    currency: 'ETH',
    currentAmount: 28,
    donors: 512,
    endDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
  },
];

export default function Home() {
  return (
    <div className="space-y-12">
      <section className="text-center bg-card p-8 rounded-xl shadow-md">
        <h1 className="text-4xl md:text-5xl font-bold font-headline tracking-tight text-primary">
          Decentralized Crowdfunding for a Better Future
        </h1>
        <p className="mt-4 max-w-2xl mx-auto text-lg text-foreground/80">
          Support innovative projects and transparent causes directly with cryptocurrency. Your contribution makes a real difference.
        </p>
        <div className="mt-8 flex justify-center gap-4">
          <Button asChild size="lg">
            <Link href="#campaigns">Explore Campaigns</Link>
          </Button>
          <Button asChild size="lg" variant="secondary">
            <Link href="/create-campaign">
              <Rocket className="mr-2" /> Start a Campaign
            </Link>
          </Button>
        </div>
      </section>

      <section id="campaigns" className="space-y-6">
        <h2 className="text-3xl font-bold font-headline text-center">
          Active Campaigns
        </h2>
        {campaigns.length > 0 ? <CampaignGrid campaigns={campaigns} /> : <p className="text-center text-foreground/70">No active campaigns yet.</p>}
      </section>

       <section id="completed-campaigns" className="space-y-6">
        <h2 className="text-3xl font-bold font-headline text-center">
          Successfully Funded
        </h2>
        {completedCampaigns.length > 0 ? <CampaignGrid campaigns={completedCampaigns} /> : <p className="text-center text-foreground/70">No completed campaigns yet.</p>}
      </section>
    </div>
  );
}
