import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Rocket, Bot, ShieldCheck, Users, Zap, BrainCircuit } from "lucide-react";
import { CampaignGrid } from "@/components/campaigns/campaign-grid";
import { Campaign } from "@/components/campaigns/campaign-card";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const campaigns: Campaign[] = [
  {
    id: 'sumatra-flood-1',
    title: 'Sumatra Flood Disaster Relief',
    description: 'Urgent aid needed for families affected by the devastating floods in Sumatra.',
    longDescription: 'Recent flash floods have displaced thousands of families in Sumatra, destroying homes and livelihoods. This fund will provide immediate relief including clean water, food, medical supplies, and temporary shelter. All transactions are transparently recorded on the blockchain.',
    imageId: 'img-sumatra-flood',
    goal: 50,
    currency: 'ETH',
    currentAmount: 18,
    donors: 320,
    endDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active',
  },
  {
    id: 'palestine-kids-2',
    title: 'Palestine Kids Support',
    description: 'Providing essential educational and medical supplies for children in Palestine.',
    longDescription: 'This campaign is dedicated to supporting the children affected by the ongoing crisis in Palestine. Funds will be used to provide educational materials, medical aid, and psychological support to help them build a better future. Your donation can make a world of difference.',
    imageId: 'img-palestine-kids',
    goal: 100,
    currency: 'BTC',
    currentAmount: 45,
    donors: 850,
    endDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active',
  },
   {
    id: 'art-generator-3',
    title: 'Chroma Collective: AI-Generated Art NFTs',
    description: 'A platform for creating and minting unique art pieces generated by collaborative AI models.',
    longDescription: 'Chroma Collective empowers artists and collectors to collaborate with AI. Our platform uses generative models trained on classical and modern art to produce stunning, unique digital creations. Each piece can be minted as an NFT, with shared ownership between the human prompter and the AI, creating a new paradigm for digital art.',
    imageId: 'img-art-ai',
    goal: 75,
    currency: 'ETH',
    currentAmount: 61,
    donors: 320,
    endDate: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active',
  },
];

const completedCampaigns: Campaign[] = [
    {
    id: 'open-source-library-4',
    title: 'Ethos.js: Open-Source Web3 Library',
    description: 'Successfully funded a new lightweight library for simpler smart contract interactions.',
    longDescription: 'Ethos.js was created to simplify the developer experience in Web3. Thanks to our 500+ backers, we have developed a powerful, lightweight JavaScript library that abstracts away the complexities of blockchain interaction, making it easier than ever to build decentralized applications. The library is now open-source and available on NPM.',
    imageId: 'img-open-source',
    goal: 25,
    currency: 'ETH',
    currentAmount: 28,
    donors: 512,
    endDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
  },
];

const FeatureCard = ({ icon, title, description }: { icon: React.ReactNode, title: string, description: string }) => (
  <Card className="bg-card/50 border-transparent hover:border-primary/50 hover:bg-card transition-all duration-300 transform hover:-translate-y-1">
    <CardHeader className="flex flex-row items-center gap-4 pb-4">
      <div className="bg-primary/10 text-primary p-3 rounded-full">{icon}</div>
      <CardTitle className="text-xl font-headline">{title}</CardTitle>
    </CardHeader>
    <CardContent>
      <p className="text-foreground/70">{description}</p>
    </CardContent>
  </Card>
);

export default function Home() {
  return (
    <div className="space-y-20">
      <section className="relative text-center py-20 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-t from-background via-background/80 to-transparent z-0"></div>
        <div className="absolute inset-x-0 top-0 h-96 w-full bg-[radial-gradient(ellipse_50%_50%_at_50%_-20%,_hsl(var(--primary)/0.3),_transparent)] z-0"></div>
        
        <div className="container relative z-10">
          <h1 className="text-4xl md:text-6xl font-bold font-headline tracking-tight">
            The Future of Funding is <span className="text-primary">Decentralized</span>.
          </h1>
          <p className="mt-6 max-w-2xl mx-auto text-lg text-foreground/80">
            Launch your vision or fund the next big thing with CriptoFund—the AI-powered, fully transparent crowdfunding platform on the blockchain.
          </p>
          <div className="mt-8 flex justify-center gap-4">
            <Button asChild size="lg" className="btn-primary">
              <Link href="#campaigns">Explore Campaigns</Link>
            </Button>
            <Button asChild size="lg" variant="secondary">
              <Link href="/create-campaign">
                <Rocket className="mr-2" /> Start a Campaign
              </Link>
            </Button>
          </div>
        </div>
      </section>

      <section className="container mx-auto text-center">
        <h2 className="text-3xl font-bold font-headline mb-4">How It Works</h2>
        <p className="text-foreground/70 max-w-2xl mx-auto mb-10">Three simple steps to bring ideas to life on the blockchain.</p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <FeatureCard 
            icon={<Zap size={24} />} 
            title="1. Create or Discover" 
            description="Launch a campaign in minutes with our AI assistant or browse innovative projects." />
          <FeatureCard 
            icon={<Rocket size={24} />} 
            title="2. Fund with Crypto" 
            description="Donate securely using ETH or BTC via your MetaMask wallet in just a few clicks." />
          <FeatureCard 
            icon={<ShieldCheck size={24} />} 
            title="3. Track the Impact" 
            description="Follow progress on-chain. All donations and milestones are transparent and verifiable." />
        </div>
      </section>

      <section id="campaigns" className="space-y-6">
        <h2 className="text-3xl font-bold font-headline text-center">
          Active Campaigns
        </h2>
        {campaigns.length > 0 ? <CampaignGrid campaigns={campaigns} /> : <p className="text-center text-foreground/70">No active campaigns yet.</p>}
      </section>

      <section className="container mx-auto">
        <h2 className="text-3xl font-bold font-headline text-center mb-10">Why CriptoFund?</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-8">
            <FeatureCard 
              icon={<Bot size={24} />}
              title="AI Campaign Craft"
              description="From a simple idea to a fully-fledged campaign in seconds. Our AI helps you craft the perfect pitch to attract backers."
            />
             <FeatureCard 
              icon={<BrainCircuit size={24} />}
              title="AI Donation Assistant"
              description="Set your monthly budget and preferred causes. Our AI automatically allocates your funds to relevant campaigns each month."
            />
            <FeatureCard 
              icon={<ShieldCheck size={24} />}
              title="Enterprise-Level Security"
              description="Built on audited smart contracts, every donation is cryptographically secure. Donors can track their funds transparently on the blockchain from donation to impact."
            />
            <FeatureCard 
              icon={<Users size={24} />}
              title="Community-Driven"
              description="Earn 'Vibe Coins' for your contributions and become part of a community that supports innovation."
            />
        </div>
      </section>

       <section id="completed-campaigns" className="space-y-6">
        <h2 className="text-3xl font-bold font-headline text-center">
          Successfully Funded
        </h2>
        {completedCampaigns.length > 0 ? <CampaignGrid campaigns={completedCampaigns} /> : <p className="text-center text-foreground/70">No completed campaigns yet.</p>}
      </section>

      <section className="text-center py-20 bg-primary/5 rounded-xl">
        <div className="container">
          <h2 className="text-3xl md:text-4xl font-bold font-headline">Ready to Make an Impact?</h2>
          <p className="mt-4 max-w-xl mx-auto text-foreground/80">
            Join a community that's funding the future. Discover innovative projects and support them with crypto. Your next great contribution is just a click away.
          </p>
          <div className="mt-8">
            <Button asChild size="lg" className="btn-primary">
              <Link href="#campaigns">Donate Now</Link>
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
}
